/**
 * CAREER_MAPPING_BUILDER.js — Script chạy 1 lần để đọc KB và sinh ra static table
 * Phân tích: life_path[n].career + destiny_number[n].career -> score 5 nhóm ngành
 * Kết quả hardcode vào app.js -> deterministic, không AI
 *
 * 5 NHÓM NGÀNH (Holland-inspired, Việt hóa):
 *   KT  = Kỹ thuật & Công nghệ
 *   KD  = Kinh doanh & Quản lý
 *   XH  = Xã hội & Con người
 *   ST  = Sáng tạo & Nghệ thuật
 *   NC  = Nghiên cứu & Khoa học
 */

'use strict';
const KB = require('../numerology_knowledge_base.json');

// ── Keyword → nhóm ngành ─────────────────────────────────────────────────────
const KEYWORD_MAP = {
  // KT — Kỹ thuật & Công nghệ
  KT: ['kỹ thuật','kỹ sư','công nghệ','xây dựng','kiến trúc','lập trình',
       'kỹ nghệ','phát minh','thi công','cơ khí','điện tử','it '],
  // KD — Kinh doanh & Quản lý
  KD: ['kinh doanh','doanh nhân','quản lý','quản trị','lãnh đạo','tài chính',
       'ngân hàng','bất động sản','khởi nghiệp','ông chủ','thương mại',
       'xuất nhập khẩu','tiếp thị','quảng cáo','marketing','bán hàng',
       'phi lợi nhuận','chính trị'],
  // XH — Xã hội & Con người
  XH: ['giảng dạy','tư vấn','tâm lý','chăm sóc','y tế','sức khỏe','khách sạn',
       'du lịch','hòa giải','ngoại giao','xã hội','giáo dục','luật pháp',
       'luật sư','tâm linh'],
  // ST — Sáng tạo & Nghệ thuật
  ST: ['nghệ sĩ','âm nhạc','nhạc sĩ','diễn viên','nhà văn','đầu bếp','vũ công',
       'thiết kế','thời trang','nội thất','nghệ thuật','làm phim','thơ','báo chí',
       'diễn giả','truyền thông','dẫn chương trình','sáng tạo','giải trí'],
  // NC — Nghiên cứu & Khoa học
  NC: ['nghiên cứu','khoa học','phân tích','sử học','bảo tàng','thần học',
       'triết học','tri thức','học thuật','giáo viên','kế toán','ngôn ngữ'],
};

// ── Hàm tính điểm từ chuỗi career ────────────────────────────────────────────
function scoreCareerString(str) {
  const lower = str.toLowerCase();
  const scores = { KT: 0, KD: 0, XH: 0, ST: 0, NC: 0 };
  for (const [group, keywords] of Object.entries(KEYWORD_MAP)) {
    for (const kw of keywords) {
      if (lower.includes(kw)) scores[group]++;
    }
  }
  return scores;
}

// ── Tổng hợp điểm cả LP và DEST cho mỗi số ───────────────────────────────────
function buildEntry(num) {
  const lpStr  = KB.life_path[num]?.career || '';
  const destStr = KB.destiny_number[num]?.career || '';

  const s1 = scoreCareerString(lpStr);
  const s2 = scoreCareerString(destStr);

  const combined = {};
  for (const g of Object.keys(s1)) combined[g] = s1[g] + s2[g];

  // Nếu tất cả = 0 thì gán bằng nhau
  const total = Object.values(combined).reduce((a, b) => a + b, 0);
  if (total === 0) return { KT: 20, KD: 20, XH: 20, ST: 20, NC: 20 };

  // Normalize -> %
  const pct = {};
  let sum = 0;
  const groups = Object.keys(combined);
  for (const g of groups) {
    pct[g] = Math.round((combined[g] / total) * 100);
    sum += pct[g];
  }
  // Fix rounding error -> thêm vào nhóm cao nhất
  if (sum !== 100) {
    const maxGroup = groups.reduce((a, b) => (pct[a] >= pct[b] ? a : b));
    pct[maxGroup] += (100 - sum);
  }

  return pct;
}

// ── Build toàn bộ table ────────────────────────────────────────────────────────
const NUMS = ['1','2','3','4','5','6','7','8','9','11','22'];
const TABLE = {};
for (const n of NUMS) {
  TABLE[n] = buildEntry(n);
}

console.log('// ─── STATIC CAREER GROUP TABLE (pre-computed from KB) ─────────────');
console.log('// Generated by: node scripts/career_mapping_builder.js');
console.log('// Based on: life_path[n].career + destiny_number[n].career keyword analysis');
console.log('// Groups: KT=Kỹ thuật & CN, KD=Kinh doanh & QL, XH=Xã hội & CN, ST=Sáng tạo & NT, NC=Nghiên cứu & KH');
console.log('const CAREER_TABLE = ' + JSON.stringify(TABLE, null, 2) + ';');
console.log('\n// Verification (all should sum to 100):');
for (const n of NUMS) {
  const sum = Object.values(TABLE[n]).reduce((a, b) => a + b, 0);
  console.log(`//   LP/D ${n.padEnd(2)}: ${JSON.stringify(TABLE[n])} → sum=${sum}`);
}
